version: '3.8'

networks:
  monitoring: {}
  nano-network:
    external:
      name: ${NANO_NETWORK:-nano-network}
    
volumes:
  grafana_data: {}
  prometheus_data: {}

services:
  nano-prom-exporter:
    build: .
    restart: unless-stopped
    environment:
      - NANO_PROM_DEBUG=1
    command: --rpchost ${RPC_HOST:-host.docker.internal} --rpc_port ${RPC_PORT:-7076} --push_gateway http://pushgateway:9091
    depends_on:
      - pushgateway
    networks:
      - monitoring
      - nano-network
    profiles:
      - exporter
      
  pushgateway:
    image: prom/pushgateway:latest
    restart: unless-stopped
    expose:
      - 9091
    networks:
      - monitoring
    ports:
      - 9091:9091
    profiles:
      - grafana-stack
      - exporter

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    # tmpfs: /prometheus:uid=99
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    networks:
      - monitoring
    ports:
      - 9090:9090
    profiles:
      - grafana-stack
      - exporter

  grafana:
    # 8.3.3 - terrible dashboard graph flashing
    image: grafana/grafana:8.3.2
    restart: unless-stopped
    user: "472"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    # env_file:
      # - ./grafana/config.monitoring
    networks:
      - monitoring
    profiles:
      - grafana-stack
      - exporter