version: '3.8'

networks:
  monitoring:
    
volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  pushgateway:
    image: prom/pushgateway:latest
    container_name: pushgateway
    restart: unless-stopped
    expose:
      - 9091
    networks:
      - monitoring
    ports:
      - 9091:9091

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    networks:
      - monitoring
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    user: "472"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    # env_file:
      # - ./grafana/config.monitoring
    networks:
      - monitoring
  
  nano-prom-exporter:
    build: .
    container_name: nano-prom-exporter
    restart: unless-stopped
    environment:
      - NANO_PROM_DEBUG=1
    command: --rpchost host.docker.internal --push_gateway http://pushgateway:9091
    depends_on:
      - pushgateway
    networks:
      - monitoring